# Generated by Django 3.2.9 on 2022-04-17 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='phone_number',
            new_name='phone_no',
        ),
    ]
